server:
  port: ":8081"
  read_timeout: 10s
  write_timeout: 10s
  mode: "release"  # Options: "debug", "release"

postgresql:
  debugMode: true
  database: "wms"
  maxOpenConns: 10
  maxIdleConns: 2
  master:
    host: "localhost"
    port: 5432
    username: "root"
    password: "p@ssword"
  slaves: []



